blank_issues_enabled: false
contact_links:
  - name: Support Question
    url: https://nova.laravel.com/docs/2.0/contributions.html#support-questions
  - name: Documentation Issue
    url: https://github.com/laravel/nova-docs
    about: For documentation issues, open a pull request in the laravel/nova-docs repository
